#ifndef PHYSICS_BULLET_GLOBAL_H
#define PHYSICS_BULLET_GLOBAL_H

#include <build/importexport.h>

#if defined(PHYSICS_BULLET_LIBRARY)
#define PHYSICS_BULLET_SHARED_EXPORT SIMPEX_DECL_EXPORT
#else
#define PHYSICS_BULLET_SHARED_EXPORT SIMPEX_DECL_IMPORT
#endif

#endif // PHYSICS_BULLET_GLOBAL_H
