#ifndef LOADER_ASSIMP_GLOBAL_H
#define LOADER_ASSIMP_GLOBAL_H

#include <build/importexport.h>

#if defined(LOADER_ASSIMP_LIBRARY)
#define LOADER_ASSIMP_GLOBAL_SHARED_EXPORT SIMPEX_DECL_EXPORT
#else
#define LOADER_ASSIMP_GLOBAL_SHARED_EXPORT SIMPEX_DECL_IMPORT
#endif

#endif // LOADER_ASSIMP_GLOBAL_H
