#ifndef SCENES_LOADER_ASSIMP_GLOBAL_H
#define SCENES_LOADER_ASSIMP_GLOBAL_H

#include <build/importexport.h>

#if defined(SCENES_LOADER_ASSIMP_LIBRARY)
#define SCENES_LOADER_ASSIMP_GLOBAL_SHARED_EXPORT SIMPEX_DECL_EXPORT
#else
#define SCENES_LOADER_ASSIMP_GLOBAL_SHARED_EXPORT SIMPEX_DECL_IMPORT
#endif

#endif // SCENES_LOADER_ASSIMP_GLOBAL_H
