layout (local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

#include<camera.glsl>
#include<cluster_node.glsl>

#include<math/bounding_box.glsl>
#include<math/utils.glsl>

void main(void)
{
	const uvec3 clusterSize = cameraClusterSize();
    if (all(lessThan(gl_GlobalInvocationID, clusterSize)))
    {
		const uint ID_X = gl_GlobalInvocationID.x;
		const uint ID_Y = gl_GlobalInvocationID.y;
		const uint ID_Z = gl_GlobalInvocationID.z;
		
		const mat4x4 projectionMatrixInverted = cameraProjectionMatrixInverted();
		BoundingBox bb = makeEmptyBoundingBox();
		for (uint i = 0u; i < BOUNDING_BOX_POINTS_COUNT; ++i)
		{
			vec2 NDC_XY = vec2(float(ID_X + bitfieldExtract(i, 0, 1)), float(ID_Y + bitfieldExtract(i, 1, 1)));
			NDC_XY /= vec2(clusterSize.xy);
			NDC_XY = ZO2NO(NDC_XY);

			const vec3 nearPoint = projectPoint(projectionMatrixInverted, vec3(NDC_XY, -1.0f));
			const vec3 farPoint = projectPoint(projectionMatrixInverted, vec3(NDC_XY, 1.0f));

			const float linearZ = float(ID_Z + bitfieldExtract(i, 2, 1)) / float(clusterSize.z);
			bb = boundingBoxExpand(bb, mix(nearPoint, farPoint, linearZ));
		}

		const uint clusterNodeID = ID_X + ID_Y * clusterSize.x + ID_Z * clusterSize.x * clusterSize.y;
		clusterNodeInitialize(clusterNodeID, bb);
    }
}