layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

#include<camera.glsl>
#include<counters.glsl>
#include<drawable.glsl>
#include<draw_data.glsl>
#include<geometry.glsl>
#include<draw_data_visibility.glsl>
#include<indirect_commands.glsl>
#include<material.glsl>
#include<mesh.glsl>
#include<render_info.glsl>

#include<math/bounding_box.glsl>
#include<math/classifications.glsl>
#include<math/oriented_bounding_box.glsl>
#include<math/transform.glsl>

#define DISABLED_DRAW_DATA_CULLING_ALGORITHM 0u
#define SUPER_FAST_DRAW_DATA_CULLING_ALGORITHM 1u
#define FAST_DRAW_DATA_CULLING_ALGORITHM 2u
#define CORRECT_DRAW_DATA_CULLING_ALGORITHM 3u

#ifndef DRAW_DATA_CULLING_ALGORITHM
	#define DRAW_DATA_CULLING_ALGORITHM SUPER_FAST_DRAW_DATA_CULLING_ALGORITHM
#endif

layout (std430) buffer ssbo_opaqueDrawDataRenderCommandsBuffer {
	DrawElementsIndirectCommand opaqueDrawDataRenderCommands[];
};

layout (std430) buffer ssbo_transparentDrawDataRenderCommandsBuffer {
	DrawElementsIndirectCommand transparentDrawDataRenderCommands[];
};

bool testHiZ(in OrientedBoundingBox obbVS)
{
	const BoundingBox aabbVS = orientedBoundingBoxCircumscribedBoundingBox(obbVS);
	const BoundingBox aabbNDC = cameraProjectBoundingBox(aabbVS);
	return geometryTestBoundingBox(aabbNDC);
}

void main(void)
{
    if (all(lessThan(gl_GlobalInvocationID, uvec3(renderInfoDrawDataCount(), 1u, 1u))))
    {
		const uint drawDataID = gl_GlobalInvocationID[0u];
		const uint drawableID = drawDataDrawableID(drawDataID);
		
		if (drawableID != 0xFFFFFFFFu)
		{
			const uint meshID = drawableMeshID(drawableID);
			const uint materialID = drawableMaterialID(drawableID);
			if ((meshID != 0xFFFFFFFFu) && (materialID != 0xFFFFFFFFu))
			{
				const BoundingBox localBoundingBox = meshBoundingBox(meshID);
				
				if (!isBoundingBoxEmpty(localBoundingBox))
				{	
					const OrientedBoundingBox orientedBoundingBox = transformOrientedBoundingBox(
						transformMult(cameraViewTransform(), drawDataTransform(drawDataID)),
						makeOrientedBoundingBox(localBoundingBox));
					
					const vec3 frustumPoints[FRUSTUM_POINTS_COUNT] = cameraFrustumPoints();
					
					#if (DRAW_DATA_CULLING_ALGORITHM == DISABLED_DRAW_DATA_CULLING_ALGORITHM)
						bool isBoundingBoxVisible = true;
					#elif (DRAW_DATA_CULLING_ALGORITHM == SUPER_FAST_DRAW_DATA_CULLING_ALGORITHM)
						bool isBoundingBoxVisible = orientedBoundingBoxVsFrustumSuperFast(
							orientedBoundingBox,
							cameraFrustumFaceNormalLines(),
							cameraFrustumRanges());
					#elif (DRAW_DATA_CULLING_ALGORITHM == FAST_DRAW_DATA_CULLING_ALGORITHM)
						bool isBoundingBoxVisible = orientedBoundingBoxVsFrustumFast(
							orientedBoundingBox,
							cameraFrustumFaceNormalLines(),
							cameraFrustumRanges(),
							frustumPoints);
					#elif (DRAW_DATA_CULLING_ALGORITHM == CORRECT_DRAW_DATA_CULLING_ALGORITHM)
						bool isBoundingBoxVisible = orientedBoundingBoxVsFrustum(
							orientedBoundingBox,
							cameraFrustumFaceNormalLines(),
							cameraFrustumRanges(),
							frustumPoints,
							cameraFrustumEdgeDirections());
					#else
						error!!!
					#endif
					
					
					if (isBoundingBoxVisible)
					{							
						const uint drawDataVisisbilityFrameIndex = countersDrawDataVisisbilityFrameIndex();
						const bool wasDrawDataVisible = drawDataVisibilityCheckPreviousFrame(drawDataID, drawDataVisisbilityFrameIndex);
						const bool isDrawDataVisible = testHiZ(orientedBoundingBox);
						const bool isDrawDataTransparent = isMaterialTransparent(materialID);
						
						if ((!wasDrawDataVisible || isDrawDataTransparent) && isDrawDataVisible)
						{
							const DrawElementsIndirectCommand command = DrawElementsIndirectCommand(
								meshElementDataSize(meshID),
								1u,
								meshElementDataOffset(meshID),
								0,
								drawDataID);
									
							if (isDrawDataTransparent)
							{
								const uint commandID = countersGenerateTransparentDrawDataRenderCommandID();
								transparentDrawDataRenderCommands[commandID] = command;
							}
							else
							{
								const uint commandID = countersGenerateOpaqueDrawDataRenderCommandID();
								opaqueDrawDataRenderCommands[commandID] = command;
							}
						}
						
						drawDataVisibilitySetCurrentFrame(drawDataID, isDrawDataVisible, drawDataVisisbilityFrameIndex);
					}
				}
			}
		}
    }
}