layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

#include<camera.glsl>
#include<drawable.glsl>
#include<draw_data.glsl>
#include<geometry.glsl>
#include<hierarchical_z.glsl>
#include<indirect_commands.glsl>
#include<material.glsl>
#include<mesh.glsl>
#include<render_info.glsl>

#include<math/bounding_box.glsl>
#include<math/classifications.glsl>
#include<math/oriented_bounding_box.glsl>
#include<math/transform.glsl>

#define DISABLED_DRAW_DATA_CULLING_ALGORITHM 0u
#define SUPER_FAST_DRAW_DATA_CULLING_ALGORITHM 1u
#define FAST_DRAW_DATA_CULLING_ALGORITHM 2u
#define CORRECT_DRAW_DATA_CULLING_ALGORITHM 3u

#ifndef DRAW_DATA_CULLING_ALGORITHM
	#define DRAW_DATA_CULLING_ALGORITHM SUPER_FAST_DRAW_DATA_CULLING_ALGORITHM
#endif

layout (std430) buffer ssbo_opaqueDrawDataRenderCommandsBuffer {
	DrawElementsIndirectCommand opaqueDrawDataRenderCommands[];
};

layout (std430) buffer ssbo_transparentDrawDataRenderCommandsBuffer {
	DrawElementsIndirectCommand transparentDrawDataRenderCommands[];
};

bool testHiZ(in OrientedBoundingBox obb)
{
	const mat4x4 projectionMatrix = cameraProjectionMatrix();
	BoundingBox ndcAABB = makeEmptyBoundingBox();
	float maxZ = -FLT_MAX;
	for (uint i = 0u; i < BOUNDING_BOX_POINTS_COUNT; ++i)
	{
		const vec3 obbPointVS = orientedBoundingBoxPoint(obb, i);
		maxZ = max(maxZ, obbPointVS[2u]);
		const vec3 obbPointNDC = projectPoint(projectionMatrix, obbPointVS);
		ndcAABB = boundingBoxExpand(ndcAABB, obbPointNDC);
	}
	
	const vec2 minUV = clamp(NO2ZO(vec2(boundingBoxMinPoint(ndcAABB))), vec2(0.0f), vec2(1.0f));
	const vec2 maxUV = clamp(NO2ZO(vec2(boundingBoxMaxPoint(ndcAABB))), vec2(0.0f), vec2(1.0f));
	
	const float closestDepth = clamp(NO2ZO(projectPoint(projectionMatrix, vec3(0.0f, 0.0f, maxZ))[2u]), 0.0f, 1.0f);
	
	const vec2 boxSizePixels = (maxUV - minUV) * vec2(renderInfoViewportSize());
	const float maxBoxSize = max(boxSizePixels.x, boxSizePixels.y);
	
	const float maxLevel = float(textureQueryLevels(sampler2D(GBuffer.depthTextureHandle)) - 1);
	const float mipLevel = clamp(ceil(log2(maxBoxSize)), 0.0f, maxLevel);
	
	const vec2 textureSizeAtMip = vec2(textureSize(sampler2D(GBuffer.depthTextureHandle), int(mipLevel)));
	const vec2 texelHalfSize = 0.5f / textureSizeAtMip;
	
	const vec2 sampleMin = clamp(minUV - texelHalfSize, vec2(0.0f), vec2(1.0f));
	const vec2 sampleMax = clamp(maxUV + texelHalfSize, vec2(0.0f), vec2(1.0f));
	
	const float d0 = textureLod(sampler2D(GBuffer.depthTextureHandle), vec2(sampleMin.x, sampleMin.y), mipLevel).r;
	const float d1 = textureLod(sampler2D(GBuffer.depthTextureHandle), vec2(sampleMax.x, sampleMin.y), mipLevel).r;
	const float d2 = textureLod(sampler2D(GBuffer.depthTextureHandle), vec2(sampleMin.x, sampleMax.y), mipLevel).r;
	const float d3 = textureLod(sampler2D(GBuffer.depthTextureHandle), vec2(sampleMax.x, sampleMax.y), mipLevel).r;
	const float maxDepth = max(max(d0, d1), max(d2, d3));
	
	return (closestDepth - 0.05f <= maxDepth);
}

void main(void)
{
    if (all(lessThan(gl_GlobalInvocationID, uvec3(renderInfoDrawDataCount(), 1u, 1u))))
    {
		const uint drawDataID = gl_GlobalInvocationID[0u];
		const uint drawableID = drawDataDrawableID(drawDataID);
		
		if (drawableID != 0xFFFFFFFFu)
		{
			const uint meshID = drawableMeshID(drawableID);
			const uint materialID = drawableMaterialID(drawableID);
			if ((meshID != 0xFFFFFFFFu) && (materialID != 0xFFFFFFFFu))
			{
				const BoundingBox localBoundingBox = meshBoundingBox(meshID);
				
				if (!isBoundingBoxEmpty(localBoundingBox))
				{	
					const OrientedBoundingBox orientedBoundingBox = transformOrientedBoundingBox(
						transformMult(cameraViewTransform(), drawDataTransform(drawDataID)),
						makeOrientedBoundingBox(localBoundingBox));
					
					const vec3 frustumPoints[FRUSTUM_POINTS_COUNT] = cameraFrustumPoints();
					
					#if (DRAW_DATA_CULLING_ALGORITHM == DISABLED_DRAW_DATA_CULLING_ALGORITHM)
						bool isBoundingBoxVisible = true;
					#elif (DRAW_DATA_CULLING_ALGORITHM == SUPER_FAST_DRAW_DATA_CULLING_ALGORITHM)
						bool isBoundingBoxVisible = orientedBoundingBoxVsFrustumSuperFast(
							orientedBoundingBox,
							cameraFrustumFaceNormalLines(),
							cameraFrustumRanges());
					#elif (DRAW_DATA_CULLING_ALGORITHM == FAST_DRAW_DATA_CULLING_ALGORITHM)
						bool isBoundingBoxVisible = orientedBoundingBoxVsFrustumFast(
							orientedBoundingBox,
							cameraFrustumFaceNormalLines(),
							cameraFrustumRanges(),
							frustumPoints);
					#elif (DRAW_DATA_CULLING_ALGORITHM == CORRECT_DRAW_DATA_CULLING_ALGORITHM)
						bool isBoundingBoxVisible = orientedBoundingBoxVsFrustum(
							orientedBoundingBox,
							cameraFrustumFaceNormalLines(),
							cameraFrustumRanges(),
							frustumPoints,
							cameraFrustumEdgeDirections());
					#else
						error!!!
					#endif
					
					
					if (isBoundingBoxVisible)
					{							
						const bool wasDrawDataVisible = hierarchicalZWasDrawDataVisible(drawDataID);
						const bool isDrawDataVisible = testHiZ(orientedBoundingBox);
						const bool isDrawDataTransparent = isMaterialTransparent(materialID);
						
						if ((!wasDrawDataVisible || isDrawDataTransparent) && isDrawDataVisible)
						{
							const DrawElementsIndirectCommand command = DrawElementsIndirectCommand(
								meshElementDataSize(meshID),
								1u,
								meshElementDataOffset(meshID),
								0,
								drawDataID);
									
							if (isDrawDataTransparent)
							{
								const uint commandID = hierarchicalZGenerateTransparentDrawDataRenderCommandID();
								transparentDrawDataRenderCommands[commandID] = command;
							}
							else
							{
								const uint commandID = hierarchicalZGenerateOpaqueDrawDataRenderCommandID();
								opaqueDrawDataRenderCommands[commandID] = command;
							}
						}
						
						hierarchicalZSetDrawDataVisible(drawDataID, isDrawDataVisible);
					}
					
				}
			}
		}
    }
}