layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

#include<counters.glsl>
#include<indirect_commands.glsl>
#include<render_info.glsl>

layout (std430) buffer ssbo_shadowDataCullCommandBuffer { DispatchIndirectCommand shadowDataCullCommand; };

void main(void)
{
    if (all(lessThan(gl_GlobalInvocationID, uvec3(1u))))
	{
		const uint countX = renderInfoDrawDataCount();
		const uint countY = countersShadowsToUpdateCount();
		
		const uint workGroupSizeX = CULL_SHADOW_DATA_COMPUTE_PROGRAM_WORK_GROUP_SIZE_X;
		const uint workGroupSizeY = CULL_SHADOW_DATA_COMPUTE_PROGRAM_WORK_GROUP_SIZE_Y;
		
		const uint workGroupsCountX = (countX + workGroupSizeX - 1u) / workGroupSizeX;
		const uint workGroupsCountY = (countY + workGroupSizeY - 1u) / workGroupSizeY;
		
		shadowDataCullCommand = DispatchIndirectCommand(workGroupsCountX, workGroupsCountY, 1u);
	}
}
