layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

#include<camera.glsl>
#include<counters.glsl>
#include<indirect_commands.glsl>

layout (std430) buffer ssbo_clusterLocalLightsCommandBuffer { DispatchIndirectCommand clusterLocalLightsCommand; };

void main(void)
{
    if (all(lessThan(gl_GlobalInvocationID, uvec3(1u))))
	{
		const uint countX = cameraClusterTotalSize();
		const uint countY = countersClusterLocalLightsCount();
		
		const uint workGroupSizeX = CLUSTER_LOCAL_LIGHT_COMPUTE_PROGRAM_WORK_GROUP_SIZE_X;
		const uint workGroupSizeY = CLUSTER_LOCAL_LIGHT_COMPUTE_PROGRAM_WORK_GROUP_SIZE_Y;
		
		const uint workGroupsCountX = (countX + workGroupSizeX - 1u) / workGroupSizeX;
		const uint workGroupsCountY = (countY + workGroupSizeY - 1u) / workGroupSizeY;
		
		clusterLocalLightsCommand = DispatchIndirectCommand(workGroupsCountX, workGroupsCountY, 1u);
	}
}
