layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

#include<counters.glsl>
#include<indirect_commands.glsl>

layout (std430) buffer ssbo_skeletalAnimatedDataToUpdateCommandBuffer {
	DispatchIndirectCommand skeletalAnimatedDataToUpdateCommand;
};

void main(void)
{
    if (all(lessThan(gl_GlobalInvocationID, uvec3(1u))))
	{
		const float countX = float(countersSkeletalAnimatedDataToUpdateCount());
		const float workGroupSizeX = float(CALCULATE_BONES_TRANSFORMS_DATA_COMPUTE_PROGRAM_WORK_GROUP_SIZE_X);
		const uint workGroupsCountX = uint(ceil(countX / workGroupSizeX) + 0.5f);
		skeletalAnimatedDataToUpdateCommand = DispatchIndirectCommand(workGroupsCountX, 1u, 1u);
	}
}
