layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

#include<counters.glsl>
#include<indirect_commands.glsl>

layout (std430) buffer ssbo_shadowMapBlurCommandsBuffer { DrawArraysIndirectCommand shadowMapBlurCommands[1u]; };

void main(void)
{
    if (all(lessThan(gl_GlobalInvocationID, uvec3(1u))))
	{
		shadowMapBlurCommands[0u] = DrawArraysIndirectCommand(
			4u,
			countersShadowsToUpdateCount(),
			0u,
			0u);
	}
}
