layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

#include<camera.glsl>
#include<indirect_commands.glsl>
#include<scene_info.glsl>

layout (std430) buffer ssbo_skeletalAnimatedDataToUpdateCommandBuffer {
	DispatchIndirectCommand skeletalAnimatedDataToUpdateCommand;
};

void main(void)
{
    if (all(lessThan(gl_GlobalInvocationID, uvec3(1u))))
	{
		const vec2 cullPlaneLimits = cameraCullPlaneLimits();
		const vec2 calculatedZRange = cameraZRange();
		
		vec2 ZRange = vec2(cullPlaneLimits[0u], cullPlaneLimits[0u] + 1.f);
		if (calculatedZRange[0u] <= calculatedZRange[1u])
		{
			ZRange[0u] = max(cullPlaneLimits[0u], 0.99f * calculatedZRange[0u]);
			ZRange[1u] = min(cullPlaneLimits[1u], 1.01f * calculatedZRange[1u]);
		}
		
		cameraExpandZRange(ZRange);
		cameraUpdateMatrices(ZRange);
		
		const float skeletalAnimatedDataToUpdateCount = float(sceneInfoSkeletalAnimatedDataToUpdateCount());
		const float calculateBonesTransformsDataComputeProgramWorkGroupSizeX = float(CALCULATE_BONES_TRANSFORMS_DATA_COMPUTE_PROGRAM_WORK_GROUP_SIZE_X);
		const uint calculateBonesTransformsDataComputeProgramNumWorkGroupsX =
			uint(ceil(skeletalAnimatedDataToUpdateCount / calculateBonesTransformsDataComputeProgramWorkGroupSizeX) + 0.5f);
		skeletalAnimatedDataToUpdateCommand = DispatchIndirectCommand(calculateBonesTransformsDataComputeProgramNumWorkGroupsX, 1u, 1u);
	}
}
