#ifndef GRAPHICS_GLFW_GLOBAL_H
#define GRAPHICS_GLFW_GLOBAL_H

#include <build/importexport.h>

#if defined(GRAPHICS_GLFW_LIBRARY)
#define GRAPHICS_GLFW_SHARED_EXPORT SIMPEX_DECL_EXPORT
#else
#define GRAPHICS_GLFW_SHARED_EXPORT SIMPEX_DECL_IMPORT
#endif

#endif // GRAPHICS_GLFW_GLOBAL_H
